server:
  port: 9000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webmvc:
          routes:
          - id: PRODUK
            uri: lb://PRODUK
            predicates:
              - Path=api/produk/**
          - id: ORDER-SERVICE
            uri: lb://ORDER
            predicates:
              - Path=api/order/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost